// glasses-management-frontend/src/views/SysUser.vue
<template>
  <div class="sys-user-page">
    <div class="page-header">
      <div class="header-content">
        <h2>账号管理中心</h2>
        <p>管理商户账号状态，支持封禁、恢复、逻辑删除和彻底删除。</p>
      </div>
      <div class="header-actions">
        <el-switch v-model="includeDeleted" active-text="显示已删除" @change="fetchUsers" />
        <el-button type="primary" @click="fetchUsers" :icon="Refresh">刷新列表</el-button>
      </div>
    </div>

    <el-card class="glass-card table-card" shadow="never">
      <el-table :data="users" style="width: 100%" v-loading="loading" class="sys-user-table">
        <el-table-column prop="id" label="账号ID" width="90" />
        <el-table-column prop="username" label="用户名" min-width="140" />
        <el-table-column prop="phone" label="手机号" min-width="140" />
        <el-table-column prop="createTime" label="注册时间" min-width="180" />
        <el-table-column label="状态" width="160">
          <template #default="{ row }">
            <el-tag v-if="row.deleted" type="info">已删除</el-tag>
            <el-tag v-else-if="row.disabled" type="warning">已封禁</el-tag>
            <el-tag v-else type="success">正常</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" min-width="420" align="center" class-name="actions-column">
          <template #default="{ row }">
            <div class="table-actions">
              <template v-if="row.deleted">
                <el-button class="action-pill" size="small" @click="restoreUser(row)">恢复</el-button>
                <el-button class="action-pill action-pill--danger" size="small" @click="purgeUser(row)">彻底删除</el-button>
              </template>
              <template v-else>
                <el-button class="action-pill" size="small" @click="resetPwd(row)">重置密码</el-button>
                <el-button class="action-pill" size="small" @click="toggleDisabled(row)">
                  {{ row.disabled ? '解除封禁' : '封禁' }}
                </el-button>
                <el-button class="action-pill action-pill--danger" size="small" @click="deleteUser(row)">删除</el-button>
              </template>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Refresh } from '@element-plus/icons-vue';
import request from '../utils/request';
import { ElMessage, ElMessageBox } from 'element-plus';

const users = ref<any[]>([]);
const loading = ref(false);
const includeDeleted = ref(false);

const fetchUsers = async () => {
  loading.value = true;
  try {
    const res: any = await request.get('/sys-user/list', { params: { includeDeleted: includeDeleted.value } });
    users.value = (res as any[]) || [];
  } finally {
    loading.value = false;
  }
};

const resetPwd = async (row: any) => {
  await ElMessageBox.confirm(`确定将 ${row.username} 的密码重置为 REMOVED_RESET_PASSWORD 吗？`, '重置密码', { type: 'warning' });
  await request.post(`/sys-user/reset-password/${row.id}`);
  ElMessage.success('密码已重置为 REMOVED_RESET_PASSWORD');
  fetchUsers();
};

const toggleDisabled = async (row: any) => {
  const action = row.disabled ? '解除封禁' : '封禁';
  await ElMessageBox.confirm(`确定${action}账号 ${row.username} 吗？`, action, { type: 'warning' });
  await request.post(`/sys-user/${row.disabled ? 'enable' : 'disable'}/${row.id}`);
  ElMessage.success(`${action}成功`);
  fetchUsers();
};

const deleteUser = async (row: any) => {
  await ElMessageBox.confirm(`删除后账号 ${row.username} 将进入回收状态，可恢复。确认删除吗？`, '删除账号', { type: 'warning' });
  await request.delete(`/sys-user/${row.id}`);
  ElMessage.success('账号已删除');
  fetchUsers();
};

const restoreUser = async (row: any) => {
  await request.post(`/sys-user/restore/${row.id}`);
  ElMessage.success('账号已恢复');
  fetchUsers();
};

const purgeUser = async (row: any) => {
  await ElMessageBox.confirm(`彻底删除账号 ${row.username} 后无法恢复，确认继续吗？`, '危险操作', {
    type: 'warning',
    confirmButtonText: '彻底删除',
    cancelButtonText: '取消'
  });
  await request.delete(`/sys-user/purge/${row.id}`);
  ElMessage.success('账号已彻底删除');
  fetchUsers();
};

onMounted(fetchUsers);
</script>

<style scoped>
.sys-user-page {
  animation: fadeIn 0.4s ease-out;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  margin-bottom: 24px;
}

.page-header h2 {
  margin: 0 0 8px;
  color: var(--text-primary);
  font-size: 24px;
  letter-spacing: 0.5px;
}

.page-header p {
  margin: 0;
  color: var(--text-secondary);
}

.header-actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  align-items: center;
}

.table-card {
  border-radius: 24px;
  padding: 12px;
  background: var(--surface-overlay);
}

.table-actions {
  display: flex;
  justify-content: center;
  gap: 8px;
  flex-wrap: nowrap;
  padding: 4px 0;
  white-space: nowrap;
}

.table-actions > * {
  flex: 0 0 auto;
  position: relative;
}

.table-actions :deep(.action-pill:hover) {
  position: relative;
  z-index: 2;
}

.sys-user-table :deep(.actions-column) {
  overflow: visible;
}

.sys-user-table :deep(.actions-column .cell) {
  overflow: visible;
  padding-top: 8px;
  padding-bottom: 8px;
}

@media (max-width: 640px) {
  .page-header,
  .header-actions {
    align-items: stretch;
  }

  .page-header > :last-child,
  .header-actions > * {
    width: 100%;
  }
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>

// glasses-management-frontend-react/src/pages/SysUser/index.tsx
import React, { useState, useEffect } from 'react';
import { Card, Button, Table, Switch, Tag, Space, Modal, message } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import { sysUserAPI, SysUser } from '@/api/sysUser';

const SysUserPage: React.FC = () => {
  const [users, setUsers] = useState<SysUser[]>([]);
  const [loading, setLoading] = useState(false);
  const [includeDeleted, setIncludeDeleted] = useState(false);

  const fetchUsers = async (deleted = includeDeleted) => {
    setLoading(true);
    try {
      const res = await sysUserAPI.list(deleted);
      setUsers(res || []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers(includeDeleted);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [includeDeleted]);

  const resetPwd = (row: SysUser) => {
    Modal.confirm({
      title: '重置密码',
      content: `确定为 ${row.username} 生成一次性临时密码吗？`,
      okType: 'danger',
      onOk: async () => {
        const temp = await sysUserAPI.resetPassword(row.id);
        Modal.info({ title: '临时密码', content: <code>{String(temp)}</code> });
        message.success('密码已重置，用户下次登录必须修改');
        fetchUsers();
      },
    });
  };

  const toggleDisabled = (row: SysUser) => {
    const action = row.disabled ? '解除封禁' : '封禁';
    Modal.confirm({
      title: action,
      content: `确定${action}账号 ${row.username} 吗？`,
      onOk: async () => {
        if (row.disabled) {
          await sysUserAPI.enable(row.id);
        } else {
          await sysUserAPI.disable(row.id);
        }
        message.success(`${action}成功`);
        fetchUsers();
      },
    });
  };

  const deleteUser = (row: SysUser) => {
    Modal.confirm({
      title: '删除账号',
      content: `删除后账号 ${row.username} 将进入回收状态，可恢复。确认删除吗？`,
      okType: 'danger',
      onOk: async () => {
        await sysUserAPI.delete(row.id);
        message.success('账号已删除');
        fetchUsers();
      },
    });
  };

  const restoreUser = async (row: SysUser) => {
    await sysUserAPI.restore(row.id);
    message.success('账号已恢复');
    fetchUsers();
  };

  const purgeUser = (row: SysUser) => {
    Modal.confirm({
      title: '危险操作',
      content: `彻底删除账号 ${row.username} 后无法恢复，确认继续吗？`,
      okType: 'danger',
      okText: '彻底删除',
      onOk: async () => {
        await sysUserAPI.purge(row.id);
        message.success('账号已彻底删除');
        fetchUsers();
      },
    });
  };

  const columns = [
    { title: '账号ID', dataIndex: 'id', width: 90 },
    { title: '用户名', dataIndex: 'username' },
    { title: '手机号', dataIndex: 'phone' },
    { title: '注册时间', dataIndex: 'createTime' },
    {
      title: '状态',
      width: 120,
      render: (_: any, row: SysUser) =>
        row.deleted ? <Tag>已删除</Tag> : row.disabled ? <Tag color="warning">已封禁</Tag> : <Tag color="success">正常</Tag>,
    },
    {
      title: '操作',
      width: 380,
      align: 'center' as const,
      render: (_: any, row: SysUser) =>
        row.deleted ? (
          <div className="table-actions" style={{ justifyContent: 'center' }}>
            <Button size="small" type="primary" onClick={() => restoreUser(row)}>恢复</Button>
            <Button size="small" type="primary" danger onClick={() => purgeUser(row)}>彻底删除</Button>
          </div>
        ) : (
          <div className="table-actions" style={{ justifyContent: 'center' }}>
            <Button size="small" type="primary" onClick={() => resetPwd(row)}>重置密码</Button>
            <Button size="small" type="primary" onClick={() => toggleDisabled(row)}>{row.disabled ? '解除封禁' : '封禁'}</Button>
            <Button size="small" type="primary" danger onClick={() => deleteUser(row)}>删除</Button>
          </div>
        ),
    },
  ];

  return (
    <div className="page-shell">
      <section
        className="page-hero glass-card"
        style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}
      >
        <div>
          <h1 className="page-heading" style={{ margin: 0 }}>账号管理中心</h1>
          <p className="page-title-en">SYSTEM USER MANAGEMENT</p>
          <p style={{ margin: '6px 0 0', color: 'var(--text-secondary)' }}>
            管理商户账号状态，支持封禁、恢复、逻辑删除和彻底删除。
          </p>
        </div>
        <Space size={12}>
          <Switch
            checked={includeDeleted}
            checkedChildren="显示已删除"
            unCheckedChildren="显示已删除"
            onChange={setIncludeDeleted}
          />
          <Button type="primary" icon={<ReloadOutlined />} onClick={() => fetchUsers()}>刷新列表</Button>
        </Space>
      </section>

      <Card className="glass-card" style={{ marginTop: 18 }}>
        <Table
          rowKey="id"
          dataSource={users}
          columns={columns}
          loading={loading}
          pagination={false}
          scroll={{ x: 1080 }}
        />
      </Card>
    </div>
  );
};

export default SysUserPage;
