// glasses-management-frontend/src/views/Register.vue
<template>
  <div class="login-container">
    <div class="login-box glass-card">
      <div class="sys-title">
        <el-icon :size="28" color="var(--primary-color)"><View /></el-icon>
        <span>商户注册平台</span>
      </div>
      <p class="sys-subtitle">输入专属邀请码，完成极速注册开通</p>
      
      <el-form :model="regForm" @keyup.enter="handleRegister">
        <el-form-item>
          <el-input 
            v-model="regForm.phone" 
            placeholder="请输入您的手机号" 
            :prefix-icon="Iphone"
            size="large"
          />
        </el-form-item>
        <el-form-item>
          <el-input 
            v-model="regForm.password" 
            type="password" 
            placeholder="请设置您的登录密码" 
            :prefix-icon="Lock"
            show-password
            size="large"
          />
        </el-form-item>
        <el-form-item>
          <el-input 
            v-model="regForm.inviteCode" 
            placeholder="请输入系统邀请码" 
            :prefix-icon="Key"
            size="large"
          />
        </el-form-item>
        <div style="text-align: right; margin-top: -10px; margin-bottom: 20px;">
          <el-link type="primary" :underline="false" @click="$router.push('/login')">返回登录</el-link>
        </div>
        <el-form-item>
          <el-button 
            type="primary" 
            size="large" 
            class="login-btn" 
            @click="handleRegister" 
            :loading="loading">
            立即注册
          </el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Iphone, Lock, Key, View } from '@element-plus/icons-vue';
import { useRouter } from 'vue-router';
import request from '../utils/request';
import { ElMessage } from 'element-plus';

const router = useRouter();
const loading = ref(false);

const regForm = reactive({
  phone: '',
  password: '',
  inviteCode: ''
});

const handleRegister = async () => {
  if (!regForm.phone || !regForm.password || !regForm.inviteCode) {
    return ElMessage.warning('请完整填写注册信息');
  }
  loading.value = true;
  try {
    const res = await request.post('/auth/register', regForm);
    ElMessage.success('注册成功，请使用新账号登录！');
    router.push('/login');
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
}
</script>

<style scoped>
.login-container {
  height: 100vh;
  width: 100vw;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  overflow: hidden;
  background: transparent;
}

.login-box {
  width: 420px;
  padding: 48px;
  text-align: center;
  z-index: 10;
  background: #ffffff;
  border-radius: 12px;
  box-shadow: 0 4px 24px rgba(255, 107, 107, 0.08);
  border: 1px solid var(--border-color);
}

.sys-title {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 12px;
  font-size: 28px;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 12px;
}

.sys-subtitle {
  font-size: 15px;
  color: var(--text-secondary);
  margin-bottom: 36px;
}

.login-btn {
  width: 100%;
  letter-spacing: 2px;
  font-size: 16px;
  font-weight: 600;
  border-radius: 8px;
}
</style>

// glasses-management-frontend-react/src/pages/Register/index.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Form, Input, Button, message } from 'antd';
import { UserOutlined, LockOutlined, PhoneOutlined, KeyOutlined } from '@ant-design/icons';
import request from '@/utils/request';
import ThemeToggle from '@/components/ThemeToggle';
import '../Login/index.css';

const Register: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();

  const onFinish = async (values: any) => {
    setLoading(true);
    try {
      await request.post('/auth/register', values);
      message.success('注册成功，请登录');
      navigate('/login');
    } catch (error) {
      console.error('注册失败:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="theme-toggle-fixed">
        <ThemeToggle />
      </div>
      <div className="login-box glass-card login-anim login-anim--1">
        <div className="sys-title login-anim login-anim--2">
          <KeyOutlined style={{ fontSize: 28, color: 'var(--primary-color)' }} />
          <span>商户注册</span>
        </div>
        <p className="sys-subtitle login-anim login-anim--3">Merchant Registration</p>

        <Form form={form} onFinish={onFinish} size="large" className="login-form login-anim login-anim--4">
          <Form.Item name="inviteCode" rules={[{ required: true, message: '请输入邀请码' }]}>
            <Input prefix={<KeyOutlined />} placeholder="请输入邀请码" />
          </Form.Item>
          <Form.Item name="username" rules={[{ required: true, message: '请输入账号' }]}>
            <Input prefix={<UserOutlined />} placeholder="请输入账号" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password prefix={<LockOutlined />} placeholder="请输入密码" />
          </Form.Item>
          <Form.Item name="phone" rules={[{ required: true, message: '请输入手机号' }]}>
            <Input prefix={<PhoneOutlined />} placeholder="请输入手机号" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={loading} block className="login-btn">
              注册
            </Button>
          </Form.Item>
        </Form>

        <div className="register-footer">
          <span>已有账号？</span>
          <Link to="/login">立即登录</Link>
        </div>
      </div>
    </div>
  );
};

export default Register;
