// glasses-management-frontend-react/src/pages/Customer/index.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Table, Button, Input, Modal, Form, Radio, DatePicker, Tag, message, Popconfirm, Pagination } from 'antd';
import { PlusOutlined, SearchOutlined, EyeOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { customerAPI, Customer } from '@/api/customer';
import { useMobile } from '@/hooks/useMobile';
import './index.css';

const CustomerPage: React.FC = () => {
  const navigate = useNavigate();
  const isMobile = useMobile();
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<Customer[]>([]);
  const [total, setTotal] = useState(0);
  const [keyword, setKeyword] = useState('');
  const [current, setCurrent] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [modalVisible, setModalVisible] = useState(false);
  const [modalTitle, setModalTitle] = useState('新建顾客');
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form] = Form.useForm();

  // Set form values after modal becomes visible
  useEffect(() => {
    if (modalVisible) {
      if (editingId !== null) {
        const record = data.find((r) => r.id === editingId);
        if (record) {
          form.setFieldsValue({
            ...record,
            birthday: record.birthday ? dayjs(record.birthday) : null,
          });
        }
      } else {
        form.resetFields();
        form.setFieldsValue({ gender: 0 });
      }
    }
  }, [modalVisible, editingId, data, form]);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const res = await customerAPI.getPage({ keyword, current, size: pageSize });
      setData(res.records);
      setTotal(res.total);
    } catch (e) { /* handled */ } finally {
      setLoading(false);
    }
  }, [keyword, current, pageSize]);

  useEffect(() => { loadData(); }, [loadData]);

  const handleSearch = () => { setCurrent(1); };

  const handleAdd = () => {
    setModalTitle('新建顾客');
    setEditingId(null);
    setModalVisible(true);
  };

  const handleEdit = (record: Customer) => {
    setModalTitle('编辑顾客');
    setEditingId(record.id);
    setModalVisible(true);
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const formData = {
        ...values,
        birthday: values.birthday ? values.birthday.format('YYYY-MM-DD') : null,
      };
      if (form.getFieldValue('id')) {
        await customerAPI.update(formData);
        message.success('更新成功');
      } else {
        await customerAPI.add(formData);
        message.success('新建成功');
      }
      setModalVisible(false);
      loadData();
    } catch (e: any) {
      if (e?.code === 409 && e.data) {
        Modal.confirm({
          title: '提示',
          content: `该手机号已关联顾客：${e.data.name}。是否直接进入该顾客档案？`,
          onOk: () => {
            setModalVisible(false);
            navigate('/archive/' + e.data.id);
          },
        });
      }
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await customerAPI.delete(id);
      message.success('删除成功');
      loadData();
    } catch (e) { /* handled */ }
  };

  const genderTag = (g: number) => {
    const color = g === 1 ? 'blue' : g === 2 ? 'green' : 'default';
    const label = g === 1 ? '男' : g === 2 ? '女' : '未知';
    return <Tag color={color} className="gender-tag">{label}</Tag>;
  };

  const columns = [
    { title: '姓名', dataIndex: 'name', key: 'name' },
    { title: '手机号', dataIndex: 'phone', key: 'phone' },
    { title: '性别', dataIndex: 'gender', key: 'gender', render: (g: number) => genderTag(g) },
    { title: '生日', dataIndex: 'birthday', key: 'birthday' },
    { title: '注册时间', dataIndex: 'createTime', key: 'createTime' },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: Customer) => (
        <div className="table-actions">
          <Button className="action-pill" icon={<EyeOutlined />} onClick={() => navigate('/archive/' + record.id)}>档案</Button>
          <Button className="action-pill action-pill--edit" icon={<EditOutlined />} onClick={() => handleEdit(record)}>编辑</Button>
          <Popconfirm title="确定删除该顾客？将会级联清除其记录!" onConfirm={() => handleDelete(record.id)}>
            <Button className="action-pill action-pill--danger" icon={<DeleteOutlined />}>删除</Button>
          </Popconfirm>
        </div>
      ),
    },
  ];

  return (
    <div className="page-shell customer-page">
      <section className="page-hero glass-card customer-hero">
        <div className="hero-copy">
          <h1 className="page-heading">顾客管理</h1>
          <p className="page-title-en">Customer Management</p>
          <div className="page-toolbar">
            <Button type="primary" size="large" icon={<PlusOutlined />} onClick={handleAdd}>新建顾客</Button>
          </div>
        </div>
        <div className="hero-meta">
          <div className="meta-card">
            <span>当前顾客数</span>
            <strong>{total}</strong>
          </div>
          <div className="meta-card">
            <span>每页显示</span>
            <strong>{pageSize}</strong>
          </div>
        </div>
      </section>

      <section className="surface-panel table-card glass-card" style={{ marginTop: 24, padding: 24 }}>
        <div className="table-toolbar" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16, marginBottom: 16 }}>
          <div className="toolbar-copy">
            <h3 style={{ margin: 0 }}>顾客列表</h3>
          </div>
        </div>

        <div className="search-shell home-search-shell" style={{ marginBottom: 20 }}>
          <div className="search-icon-badge">
            <SearchOutlined style={{ fontSize: 20 }} />
          </div>
          <Input
            className="search-control"
            placeholder="搜索姓名 / 手机号"
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            onPressEnter={handleSearch}
            allowClear
          />
          <Button type="primary" className="search-submit" onClick={handleSearch}>立即搜索</Button>
        </div>

        {!isMobile ? (
          <Table
            columns={columns}
            dataSource={data}
            rowKey="id"
            loading={loading}
            pagination={false}
            className="main-table"
          />
        ) : (
          <div className="mobile-card-list">
            {data.map((row) => (
              <div key={row.id} className="mobile-card glass-card" style={{ padding: 16, marginBottom: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
                  <h4 style={{ margin: 0 }}>{row.name}</h4>
                  {genderTag(row.gender)}
                </div>
                <p style={{ margin: '4px 0', color: 'var(--text-secondary)', fontSize: 13 }}>
                  📱 {row.phone}{row.birthday ? ` · 🎂 ${row.birthday}` : ''}
                </p>
                <div style={{ display: 'flex', gap: 8, marginTop: 12, flexWrap: 'wrap' }}>
                  <Button size="small" type="primary" icon={<EyeOutlined />} onClick={() => navigate('/archive/' + row.id)}>档案</Button>
                  <Button size="small" type="primary" className="btn-edit" icon={<EditOutlined />} onClick={() => handleEdit(row)}>编辑</Button>
                  <Popconfirm title="确定删除该顾客？" onConfirm={() => handleDelete(row.id)}>
                    <Button size="small" type="primary" danger icon={<DeleteOutlined />}>删除</Button>
                  </Popconfirm>
                </div>
              </div>
            ))}
            {data.length === 0 && (
              <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-muted)' }}>暂无数据</div>
            )}
          </div>
        )}

        <div className="pagination-shell" style={{ marginTop: 16, display: 'flex', justifyContent: isMobile ? 'center' : 'flex-end' }}>
          <Pagination
            current={current}
            pageSize={pageSize}
            total={total}
            showSizeChanger={!isMobile}
            showTotal={!isMobile ? (t) => `共 ${t} 条` : undefined}
            simple={isMobile}
            pageSizeOptions={[10, 20, 50]}
            onChange={(page, size) => {
              setCurrent(page);
              setPageSize(size);
            }}
          />
        </div>
      </section>

      <Modal
        title={modalTitle}
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => setModalVisible(false)}
        width="min(92vw, 560px)"
        forceRender
      >
        <Form form={form} layout="vertical" className="customer-form" preserve={false}>
          <Form.Item name="id" hidden><Input /></Form.Item>
          <Form.Item name="name" label="姓名" rules={[{ required: true, message: '请输入姓名' }]}>
            <Input placeholder="请输入顾客姓名" />
          </Form.Item>
          <Form.Item
            name="phone"
            label="手机号"
            rules={[
              { required: true, message: '请输入手机号' },
              { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号' },
            ]}
          >
            <Input placeholder="请输入手机号码" />
          </Form.Item>
          <Form.Item name="gender" label="性别">
            <Radio.Group>
              <Radio value={1}>男</Radio>
              <Radio value={2}>女</Radio>
              <Radio value={0}>未知</Radio>
            </Radio.Group>
          </Form.Item>
          <Form.Item name="birthday" label="生日">
            <DatePicker style={{ width: '100%' }} placeholder="选择生日" />
          </Form.Item>
          <Form.Item name="remark" label="备注">
            <Input.TextArea rows={3} placeholder="其他需要补充的信息" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default CustomerPage;

// glasses-management-frontend/src/views/Customer.vue
<template>
  <div class="page-shell customer-page">
    <section class="page-hero glass-card customer-hero">
      <div class="hero-copy">
        <h1 class="page-heading">顾客管理</h1>
        <p class="page-title-en">Customer Management</p>
      </div>

      <div class="hero-meta">
        <div class="meta-card">
          <span>当前顾客数</span>
          <strong>{{ total }}</strong>
        </div>
        <div class="meta-card">
          <span>每页显示</span>
          <strong>{{ pageParams.size }}</strong>
        </div>
      </div>

      <div class="page-toolbar">
        <el-button type="primary" class="hero-btn" @click="openAddDialog">
          <el-icon><Plus /></el-icon>新建顾客
        </el-button>
      </div>
    </section>

    <section class="surface-panel table-card">
      <div class="table-toolbar">
        <div class="toolbar-copy">
          <h3>顾客列表</h3>
        </div>

        <div class="search-shell compact-search-shell query-input">
          <div class="search-icon-badge compact-search-icon">
            <el-icon :size="18"><Search /></el-icon>
          </div>
          <el-input
            v-model="keyword"
            placeholder="搜索姓名 / 手机号"
            clearable
            class="search-control compact-search-control"
            @keyup.enter="handleQuery"
          />
          <el-button class="search-submit compact-search-submit" type="primary" @click="handleQuery">立即搜索</el-button>
        </div>
      </div>
      
      <el-table :data="tableData" v-loading="loading" row-key="id" class="main-table">
        <el-table-column prop="name" label="姓名" min-width="140" />
        <el-table-column prop="phone" label="手机号" min-width="160" />
        <el-table-column label="性别" width="110">
          <template #default="scope">
            <el-tag class="gender-tag" :type="scope.row.gender === 1 ? 'primary' : (scope.row.gender === 2 ? 'success' : 'info')">
              {{ scope.row.gender === 1 ? '男' : (scope.row.gender === 2 ? '女' : '未知') }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="birthday" label="生日" min-width="130" />
        <el-table-column prop="createTime" label="注册时间" min-width="190" />
        <el-table-column label="操作" min-width="320" class-name="actions-column">
          <template #default="scope">
            <div class="table-actions">
              <el-button class="action-pill" @click="goArchive(scope.row.id)">
                <el-icon><View /></el-icon>档案
              </el-button>
              <el-button class="action-pill" @click="openEditDialog(scope.row)">
                <el-icon><Edit /></el-icon>编辑
              </el-button>
              <el-popconfirm title="确定删除该顾客？将会级联清除其记录!" @confirm="handleDelete(scope.row.id)">
                <template #reference>
                  <el-button class="action-pill action-pill--danger">
                    <el-icon><Delete /></el-icon>删除
                  </el-button>
                </template>
              </el-popconfirm>
            </div>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination-shell">
        <el-pagination
          v-model:current-page="pageParams.current"
          v-model:page-size="pageParams.size"
          :total="total"
          :page-sizes="[10, 20, 50]"
          layout="total, sizes, prev, pager, next, jumper"
          prev-text="上一页"
          next-text="下一页"
          @size-change="handleQuery"
          @current-change="loadData"
        />
      </div>
    </section>

    <el-dialog :title="dialogTitle" v-model="dialogVisible" width="min(92vw, 560px)">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="84px" class="customer-form">
        <el-form-item label="姓名" prop="name">
          <el-input v-model="form.name" placeholder="请输入顾客姓名" />
        </el-form-item>
        <el-form-item label="手机号" prop="phone">
          <el-input v-model="form.phone" placeholder="请输入手机号码" />
        </el-form-item>
        <el-form-item label="性别">
          <el-radio-group v-model="form.gender" class="gender-group">
            <el-radio :label="1">男</el-radio>
            <el-radio :label="2">女</el-radio>
            <el-radio :label="0">未知</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="生日">
          <el-date-picker
            v-model="form.birthday"
            type="date"
            value-format="YYYY-MM-DD"
            placeholder="选择生日"
            style="width: 100%"
          />
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="form.remark" type="textarea" :rows="3" placeholder="其他需要补充的信息" />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">取消</el-button>
          <el-button type="primary" @click="submitForm">确定</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import request from '../utils/request';
import { ElMessage } from 'element-plus';
import { Plus, Search, View, Edit, Delete } from '@element-plus/icons-vue';

const router = useRouter();
const tableData = ref([]);
const loading = ref(false);
const total = ref(0);
const keyword = ref('');
const pageParams = reactive({ current: 1, size: 10 });

const dialogVisible = ref(false);
const dialogTitle = ref('新建顾客');
const formRef = ref(null);
const form = reactive({
  id: null,
  name: '',
  phone: '',
  gender: 0,
  birthday: '',
  remark: ''
});

const rules = {
  name: [{ required: true, message: '请输入姓名', trigger: 'blur' }],
  phone: [
    { required: true, message: '请输入手机号', trigger: 'blur' },
    { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号', trigger: 'blur' }
  ]
};

onMounted(() => {
  loadData();
});

const handleQuery = () => {
  pageParams.current = 1;
  loadData();
};

const loadData = async () => {
  loading.value = true;
  try {
    const res: any = await request.get('/customer/page', {
      params: { keyword: keyword.value, ...pageParams }
    });
    tableData.value = res.records;
    total.value = res.total;
  } catch (e) {
    console.error(e);
  } finally {
    loading.value = false;
  }
};

const goArchive = (id) => {
  router.push('/archive/' + id);
};

const resetForm = () => {
  form.id = null;
  form.name = '';
  form.phone = '';
  form.gender = 0;
  form.birthday = '';
  form.remark = '';
};

const openAddDialog = () => {
  resetForm();
  dialogTitle.value = '新建顾客';
  dialogVisible.value = true;
};

const openEditDialog = (row) => {
  resetForm();
  Object.assign(form, row);
  dialogTitle.value = '编辑顾客';
  dialogVisible.value = true;
};

const submitForm = async () => {
  if (!formRef.value) return;
  await formRef.value.validate(async (valid) => {
    if (valid) {
      try {
        if (form.id) {
          await request.put('/customer/update', form);
          ElMessage.success('更新成功');
        } else {
          await request.post('/customer/add', form);
          ElMessage.success('新建成功');
        }
        dialogVisible.value = false;
        loadData();
      } catch (e) {
        console.error(e);
      }
    }
  });
};

const handleDelete = async (id) => {
  try {
    await request.delete('/customer/' + id);
    ElMessage.success('删除成功');
    loadData();
  } catch (e) {
    console.error(e);
  }
};
</script>

<style scoped>
.customer-page {
  padding-top: 6px;
}

.customer-hero {
  display: grid;
  grid-template-columns: minmax(0, 1.35fr) auto;
  gap: 24px;
  align-items: end;
}

.hero-copy {
  position: relative;
  z-index: 1;
}

.hero-meta {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  justify-content: flex-end;
  position: relative;
  z-index: 1;
}

.meta-card {
  min-width: 120px;
  padding: 16px 18px;
  border-radius: 20px;
  background: var(--surface-muted);
  border: 1px solid var(--border-color);
  box-shadow: 0 14px 28px rgba(37, 99, 235, 0.08);
}

.meta-card span {
  display: block;
  margin-bottom: 8px;
  color: var(--text-muted);
  font-size: 12px;
}

.meta-card strong {
  font-size: 30px;
  line-height: 1;
  color: var(--text-primary);
}

.hero-btn {
  min-width: 138px;
}

.toolbar-copy h3 {
  margin: 0;
}

.query-input {
  width: min(100%, 390px);
}

.compact-search-shell {
  padding: 10px;
  border-radius: 24px;
  gap: 10px;
  box-shadow: 0 18px 40px rgba(37, 99, 235, 0.1);
}

.compact-search-icon {
  width: 42px;
  height: 42px;
  border-radius: 14px;
}

.compact-search-submit {
  min-width: 118px;
  height: 44px !important;
  border-radius: 16px !important;
}

.gender-tag {
  border-radius: 999px;
  font-weight: 700;
  padding: 0 10px;
}

.table-actions {
  display: flex;
  gap: 10px;
  flex-wrap: nowrap;
  white-space: nowrap;
  min-width: max-content;
  align-items: center;
  padding: 4px 0;
}

.table-actions > * {
  flex: 0 0 auto;
  position: relative;
}

.table-actions :deep(.action-pill:hover) {
  position: relative;
  z-index: 2;
}

.main-table :deep(.actions-column) {
  overflow: visible;
}

.main-table :deep(.actions-column .cell) {
  overflow: visible;
  padding-top: 8px;
  padding-bottom: 8px;
}

.customer-form {
  padding-top: 10px;
}

.gender-group {
  display: flex;
  gap: 18px;
  flex-wrap: wrap;
}

@media (max-width: 960px) {
  .customer-hero {
    grid-template-columns: 1fr;
  }

  .hero-meta {
    justify-content: flex-start;
  }
}

@media (max-width: 640px) {
  .query-input {
    width: 100%;
  }

  .compact-search-submit {
    min-width: 100%;
  }

  .meta-card {
    flex: 1 1 140px;
  }

  .table-actions {
    gap: 8px;
  }
}
</style>
