// glasses-management-frontend-react/src/pages/Statistics/index.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Card, Button, Table, DatePicker, Switch, Space, message } from 'antd';
import { DownloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { statsAPI } from '@/api/stats';
import { useNavigate } from 'react-router-dom';
import { useCountUp } from '@/hooks/useCountUp';
import './index.css';

const { RangePicker } = DatePicker;

const Statistics: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [showAll, setShowAll] = useState(false);
  const [total, setTotal] = useState(0);
  const [pageParams, setPageParams] = useState({ current: 1, size: 10 });
  const [dateRange, setDateRange] = useState<[dayjs.Dayjs, dayjs.Dayjs]>([
    dayjs().startOf('month'),
    dayjs().endOf('month'),
  ]);
  const [statsData, setStatsData] = useState<{ totalRevenue: number; orderCount: number; records: any[] }>({
    totalRevenue: 0,
    orderCount: 0,
    records: [],
  });

  // Count-up animation (port of Vue useCountUp)
  const displayRevenue = useCountUp(statsData.totalRevenue || 0);
  const displayOrders = useCountUp(statsData.orderCount || 0);
  const avgValue = statsData.orderCount > 0 ? statsData.totalRevenue / statsData.orderCount : 0;
  const displayAvg = useCountUp(avgValue);

  // Pulse effect on data refresh
  const [pulsing, setPulsing] = useState(false);
  const pulseTimer = useRef<ReturnType<typeof setTimeout>>();
  const triggerPulse = () => {
    setPulsing(false);
    requestAnimationFrame(() => {
      setPulsing(true);
      if (pulseTimer.current) clearTimeout(pulseTimer.current);
      pulseTimer.current = setTimeout(() => setPulsing(false), 400);
    });
  };

  const fetchStats = useCallback(async () => {
    setLoading(true);
    try {
      const params: any = { ...pageParams, showAll };
      if (!showAll && dateRange[0] && dateRange[1]) {
        params.startDate = dateRange[0].format('YYYY-MM-DD');
        params.endDate = dateRange[1].format('YYYY-MM-DD');
      }
      const res = await statsAPI.getStats(params);
      setStatsData({
        totalRevenue: res.totalRevenue || 0,
        orderCount: res.orderCount || 0,
        records: res.records?.records || [],
      });
      setTotal(res.records?.total || 0);
      triggerPulse();
    } catch {
      message.error('获取统计数据失败');
    } finally {
      setLoading(false);
    }
  }, [pageParams, showAll, dateRange]);

  useEffect(() => {
    fetchStats();
  }, [fetchStats]);

  const handleDateChange = () => {
    setPageParams(p => ({ ...p, current: 1 }));
  };

  const handleShowAllChange = (val: boolean) => {
    setShowAll(val);
    setPageParams(p => ({ ...p, current: 1 }));
  };

  const pulseCls = pulsing ? ' stat-value--pulse' : '';

  const columns = [
    { title: '日期', dataIndex: 'salesDate' },
    { title: '单号', dataIndex: 'recordNo' },
    { title: '顾客姓名', dataIndex: 'customerName' },
    {
      title: '商品项目',
      render: (_: any, row: any) => (
        <Space size={4} wrap>
          {row.frameBrand && <span style={{ background: 'var(--primary-soft)', borderRadius: 999, padding: '2px 8px', fontSize: 12, fontWeight: 700 }}>{row.frameBrand} {row.frameModel}</span>}
          {row.lensBrand && <span style={{ background: 'var(--surface-muted)', borderRadius: 999, padding: '2px 8px', fontSize: 12, fontWeight: 700, color: 'var(--text-secondary)' }}>{row.lensBrand}</span>}
        </Space>
      ),
    },
    {
      title: '金额',
      dataIndex: 'totalAmount',
      render: (v: any) => <span style={{ color: 'var(--primary-color)', fontWeight: 800 }}>￥{v}</span>,
    },
    {
      title: '操作',
      width: 120,
      render: (_: any, row: any) => (
        <Button size="small" type="primary" onClick={() => navigate(`/archive/${row.customerId}`)}>查看详情</Button>
      ),
    },
  ];

  const handleExport = async () => {
    try {
      await statsAPI.exportRevenue(
        showAll,
        showAll ? undefined : dateRange[0].format('YYYY-MM-DD'),
        showAll ? undefined : dateRange[1].format('YYYY-MM-DD')
      );
    } catch {
      // handled by request interceptor
    }
  };

  return (
    <div className="page-shell">
      <section
        className="page-hero glass-card"
        style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}
      >
        <div>
          <h1 className="page-heading" style={{ margin: 0 }}>营收统计</h1>
          <p className="page-title-en">Revenue Statistics</p>
        </div>
        <Space wrap size={12}>
          <Switch
            checked={showAll}
            onChange={handleShowAllChange}
            checkedChildren="展示所有记录"
            unCheckedChildren="展示所有记录"
          />
          <RangePicker
            value={dateRange}
            onChange={(dates) => {
              if (dates?.[0] && dates?.[1]) {
                setDateRange([dates[0], dates[1]]);
                handleDateChange();
              }
            }}
            disabled={showAll}
          />
          <Button type="primary" icon={<DownloadOutlined />} onClick={handleExport}>导出流水</Button>
        </Space>
      </section>

      <div className="summary-grid stagger-children" style={{ margin: '20px 0' }}>
        <Card className="glass-card" style={{ padding: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
            <div className="stat-icon stat-icon--revenue">¥</div>
            <div>
              <p style={{ margin: '0 0 6px', color: 'var(--text-secondary)', fontSize: 14 }}>累计营收 (元)</p>
              <h3 className={`stat-value${pulseCls}`}>￥{displayRevenue.toFixed(2)}</h3>
            </div>
          </div>
        </Card>
        <Card className="glass-card" style={{ padding: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
            <div className="stat-icon stat-icon--orders">#</div>
            <div>
              <p style={{ margin: '0 0 6px', color: 'var(--text-secondary)', fontSize: 14 }}>订单总量 (笔)</p>
              <h3 className={`stat-value${pulseCls}`}>{Math.round(displayOrders)}</h3>
            </div>
          </div>
        </Card>
        <Card className="glass-card" style={{ padding: 8 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
            <div className="stat-icon stat-icon--average">∑</div>
            <div>
              <p style={{ margin: '0 0 6px', color: 'var(--text-secondary)', fontSize: 14 }}>平均客单价 (元)</p>
              <h3 className={`stat-value${pulseCls}`}>￥{displayAvg.toFixed(2)}</h3>
            </div>
          </div>
        </Card>
      </div>

      <Card
        className="glass-card"
        title={<h3 style={{ margin: 0 }}>收支流水明细</h3>}
      >
        <Table
          rowKey="id"
          dataSource={statsData.records}
          columns={columns}
          loading={loading}
          pagination={{
            current: pageParams.current,
            pageSize: pageParams.size,
            total,
            showTotal: (t) => `共 ${t} 条`,
            showSizeChanger: true,
            pageSizeOptions: ['10', '20', '50', '100'],
            onChange: (c, s) => setPageParams({ current: c, size: s }),
          }}
          scroll={{ x: 880 }}
        />
      </Card>
    </div>
  );
};

export default Statistics;

// glasses-management-frontend/src/views/Statistics.vue
<template>
  <div class="page-shell stats-page">
    <section class="page-hero glass-card stats-hero">
      <div class="hero-copy">
        <h1 class="page-heading">营收统计</h1>
        <p class="page-title-en">Revenue Statistics</p>
      </div>

      <div class="filter-toolbar">
        <el-switch
          v-model="showAll"
          active-text="展示所有记录"
          class="stats-switch"
          @change="handleShowAllChange"
        />
        <el-date-picker
          v-model="dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          format="YYYY-MM-DD"
          value-format="YYYY-MM-DD"
          :clearable="false"
          :disabled="showAll"
          @change="handleDateChange"
        />
        <el-button type="primary" @click="exportExcel">
          <el-icon><Download /></el-icon>导出流水
        </el-button>
      </div>
    </section>

    <section class="summary-grid">
      <div class="summary-card glass-card summary-revenue">
        <div class="card-icon">
          <el-icon><Money /></el-icon>
        </div>
        <div class="card-content">
          <p class="label">累计营收 (元)</p>
          <h3 class="value">￥{{ statsData.totalRevenue || '0.00' }}</h3>
        </div>
      </div>

      <div class="summary-card glass-card summary-orders">
        <div class="card-icon">
          <el-icon><Ticket /></el-icon>
        </div>
        <div class="card-content">
          <p class="label">订单总量 (笔)</p>
          <h3 class="value">{{ statsData.orderCount || 0 }}</h3>
        </div>
      </div>

      <div class="summary-card glass-card summary-average">
        <div class="card-icon">
          <el-icon><DataLine /></el-icon>
        </div>
        <div class="card-content">
          <p class="label">平均客单价 (元)</p>
          <h3 class="value">￥{{ avgOrderValue }}</h3>
        </div>
      </div>
    </section>

    <section class="surface-panel table-card">
      <div class="table-toolbar">
        <div class="toolbar-copy">
          <h3>收支流水明细</h3>
        </div>
      </div>

      <el-table :data="statsData.records" style="width: 100%" v-loading="loading" class="stats-table">
        <el-table-column prop="salesDate" label="日期" min-width="180" />
        <el-table-column prop="recordNo" label="单号" min-width="200" />
        <el-table-column label="商品项目" min-width="220">
          <template #default="scope">
            <div class="item-tags">
              <span class="item-tag">{{ scope.row.frameBrand }} {{ scope.row.frameModel }}</span>
              <span class="item-tag item-tag--soft">{{ scope.row.lensBrand }}</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="totalAmount" label="金额" min-width="120">
          <template #default="scope">
            <span class="price-text">￥{{ scope.row.totalAmount }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" min-width="150" class-name="actions-column">
          <template #default="scope">
            <div class="table-actions">
              <el-button class="action-pill" @click="goToArchive(scope.row.customerId)">
                查看详情
              </el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>

      <div class="pagination-shell">
        <el-pagination
          v-model:current-page="pageParams.current"
          v-model:page-size="pageParams.size"
          :total="total"
          :page-sizes="[10, 20, 50, 100]"
          layout="total, sizes, prev, pager, next"
          prev-text="上一页"
          next-text="下一页"
          @size-change="fetchStats"
          @current-change="fetchStats"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, reactive } from 'vue';
import { useRouter } from 'vue-router';
import request from '../utils/request';
import { ElMessage } from 'element-plus';
import { Money, Ticket, DataLine, Download } from '@element-plus/icons-vue';
import dayjs from 'dayjs';

const router = useRouter();
const loading = ref(false);
const showAll = ref(false);
const total = ref(0);
const pageParams = reactive({
  current: 1,
  size: 10
});

const dateRange = ref([
  dayjs().startOf('month').format('YYYY-MM-DD'),
  dayjs().endOf('month').format('YYYY-MM-DD')
]);

const statsData = ref({
  totalRevenue: 0,
  orderCount: 0,
  records: []
});

const avgOrderValue = computed(() => {
  if (!statsData.value.orderCount) return '0.00';
  return (statsData.value.totalRevenue / statsData.value.orderCount).toFixed(2);
});

onMounted(() => {
  fetchStats();
});

const handleDateChange = () => {
  pageParams.current = 1;
  fetchStats();
};

const handleShowAllChange = () => {
  pageParams.current = 1;
  fetchStats();
};

const fetchStats = async () => {
  loading.value = true;
  try {
    const params: any = {
      ...pageParams,
      showAll: showAll.value
    };
    
    if (!showAll.value && dateRange.value) {
      params.startDate = dateRange.value[0];
      params.endDate = dateRange.value[1];
    }

    const res: any = await request.get('/sales/stats', { params });
    
    if (res) {
      statsData.value.totalRevenue = res.totalRevenue;
      statsData.value.orderCount = res.orderCount;
      statsData.value.records = res.records.records;
      total.value = res.records.total;
    }
  } catch (e) {
    ElMessage.error('获取统计数据失败');
  } finally {
    loading.value = false;
  }
};

const goToArchive = (customerId: any) => {
  router.push('/archive/' + customerId);
};

const exportExcel = () => {
  let url = `http://localhost:8080/api/print/export/revenue?showAll=${showAll.value}`;
  
  if (!showAll.value && dateRange.value) {
    url += `&startDate=${dateRange.value[0]}&endDate=${dateRange.value[1]}`;
  }
  
  window.open(url, '_blank');
};
</script>

<style scoped>
.stats-page {
  padding-top: 6px;
}

.stats-hero {
  display: grid;
  grid-template-columns: minmax(0, 1.2fr) minmax(320px, 0.9fr);
  gap: 24px;
  align-items: center;
}

.filter-toolbar {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  position: relative;
  z-index: 1;
}

.toolbar-copy h3 {
  margin: 0;
}

.summary-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 20px;
}

.summary-card {
  padding: 24px;
  display: flex;
  align-items: center;
  gap: 18px;
}

.card-icon {
  width: 60px;
  height: 60px;
  border-radius: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 28px;
  color: #ffffff;
  box-shadow: 0 18px 36px rgba(37, 99, 235, 0.18);
}

.summary-revenue .card-icon {
  background: linear-gradient(135deg, #1d4ed8 0%, #2563eb 100%);
}

.summary-orders .card-icon {
  background: linear-gradient(135deg, #2563eb 0%, #38bdf8 100%);
}

.summary-average .card-icon {
  background: linear-gradient(135deg, #0f172a 0%, #2563eb 100%);
}

.label {
  margin: 0 0 6px;
  font-size: 14px;
  color: var(--text-secondary);
}

.value {
  margin: 0;
  font-size: 28px;
  font-weight: 800;
  line-height: 1.1;
  color: var(--text-primary);
}

.item-tags {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.item-tag {
  display: inline-flex;
  align-items: center;
  padding: 6px 10px;
  border-radius: 999px;
  background: var(--primary-soft);
  color: var(--primary-color);
  font-size: 12px;
  font-weight: 700;
}

.item-tag--soft {
  background: var(--surface-muted);
  color: var(--text-secondary);
}

.price-text {
  color: var(--primary-color);
  font-weight: 800;
}

.table-actions {
  display: flex;
  align-items: center;
  white-space: nowrap;
  min-width: max-content;
  padding: 4px 0;
}

.table-actions > * {
  flex: 0 0 auto;
  position: relative;
}

.table-actions :deep(.action-pill:hover) {
  position: relative;
  z-index: 2;
}

.stats-table :deep(.actions-column) {
  overflow: visible;
}

.stats-table :deep(.actions-column .cell) {
  overflow: visible;
  padding-top: 8px;
  padding-bottom: 8px;
}

@media (max-width: 1024px) {
  .stats-hero,
  .summary-grid {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 640px) {
  .filter-toolbar {
    justify-content: stretch;
  }

  .filter-toolbar > * {
    width: 100%;
  }
}
</style>
