// glasses-management-frontend-vue/src/views/Profile.vue
<template>
  <div class="page-shell profile-page">
    <section class="page-hero glass-card profile-hero">
      <div>
        <h1 class="page-heading">个人主页</h1>
        <p class="page-title-en">ACCOUNT PROFILE</p>
      </div>
      <div class="hero-profile-actions">
        <el-tag v-if="authStore.mustChangePassword" type="warning" effect="dark">建议修改默认密码</el-tag>
        <el-button class="action-pill" @click="startEdit">
          {{ editing ? '继续编辑' : '编辑资料' }}
        </el-button>
      </div>
    </section>

    <div class="profile-grid">
      <section class="profile-card glass-card identity-card">
        <div class="profile-avatar">{{ initial }}</div>
        <h2>{{ displayName }}</h2>
        <p>{{ authStore.username || '-' }}</p>
        <div class="profile-status">
          <el-tag :type="authStore.role === 'admin' ? 'danger' : 'success'">{{ roleLabel }}</el-tag>
          <el-tag v-if="authStore.disabled" type="warning">已封禁</el-tag>
          <el-tag v-else type="success">正常</el-tag>
        </div>
      </section>

      <section class="profile-card glass-card profile-detail">
        <div class="card-title-row">
          <div>
            <h3>账号信息</h3>
            <p>维护你的登录用户名、手机号和展示名称。</p>
          </div>
          <el-button v-if="!editing" class="action-pill" @click="startEdit">编辑资料</el-button>
        </div>

        <div v-if="!editing" class="detail-list">
          <div><span>显示名称</span><strong>{{ authStore.realName || '-' }}</strong></div>
          <div><span>用户名</span><strong>{{ authStore.username || '-' }}</strong></div>
          <div><span>手机号</span><strong>{{ authStore.phone || '-' }}</strong></div>
          <div><span>角色</span><strong>{{ roleLabel }}</strong></div>
          <div><span>注册时间</span><strong>{{ authStore.createTime || '-' }}</strong></div>
        </div>

        <el-form v-else :model="profileForm" label-position="top" class="profile-form">
          <el-form-item label="显示名称">
            <el-input v-model="profileForm.realName" maxlength="50" show-word-limit placeholder="用于页面展示的名称" />
          </el-form-item>
          <el-form-item label="用户名">
            <el-input v-model="profileForm.username" maxlength="30" placeholder="3-30 位，可用于登录" />
          </el-form-item>
          <el-form-item label="手机号">
            <el-input v-model="profileForm.phone" maxlength="11" placeholder="请输入手机号，也可用于登录" />
          </el-form-item>
          <div class="form-actions">
            <el-button @click="cancelEdit">取消</el-button>
            <el-button type="primary" :loading="profileLoading" @click="saveProfile">保存资料</el-button>
          </div>
        </el-form>
      </section>

      <section class="profile-card glass-card password-card">
        <h3>修改密码</h3>
        <p class="card-subtitle">建议定期更换密码，避免继续使用默认密码。</p>
        <el-form :model="pwdForm" label-position="top">
          <el-form-item label="当前密码">
            <el-input v-model="pwdForm.oldPassword" type="password" show-password placeholder="请输入当前密码" />
          </el-form-item>
          <el-form-item label="新密码">
            <el-input v-model="pwdForm.newPassword" type="password" show-password placeholder="至少 6 位" />
          </el-form-item>
          <el-form-item label="确认新密码">
            <el-input v-model="pwdForm.confirmPassword" type="password" show-password placeholder="请再次输入新密码" />
          </el-form-item>
          <el-button type="primary" :loading="passwordLoading" @click="changePassword">保存新密码</el-button>
        </el-form>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { useAuthStore } from '../store/auth';
import request from '../utils/request';

const authStore = useAuthStore();
const profileLoading = ref(false);
const passwordLoading = ref(false);
const editing = ref(false);

const profileForm = reactive({
  username: '',
  phone: '',
  realName: ''
});

const pwdForm = reactive({
  oldPassword: '',
  newPassword: '',
  confirmPassword: ''
});

const displayName = computed(() => authStore.realName || authStore.username || '-');
const initial = computed(() => (displayName.value || '用').charAt(0));
const roleLabel = computed(() => authStore.role === 'admin' ? '超级管理员' : '商户账号');

const fillProfileForm = () => {
  profileForm.username = authStore.username || '';
  profileForm.phone = authStore.phone || '';
  profileForm.realName = authStore.realName || '';
};

const startEdit = () => {
  fillProfileForm();
  editing.value = true;
};

const cancelEdit = () => {
  fillProfileForm();
  editing.value = false;
};

const saveProfile = async () => {
  const username = profileForm.username.trim();
  const phone = profileForm.phone.trim();
  const realName = profileForm.realName.trim();
  if (!username || !phone) {
    ElMessage.warning('请填写用户名和手机号');
    return;
  }
  if (username.length < 3 || username.length > 30) {
    ElMessage.warning('用户名长度需要为 3-30 位');
    return;
  }
  if (!/^1[3-9]\d{9}$/.test(phone)) {
    ElMessage.warning('请输入正确的手机号');
    return;
  }

  profileLoading.value = true;
  try {
    await request.put('/auth/profile', { username, phone, realName });
    await authStore.verifyToken();
    fillProfileForm();
    editing.value = false;
    ElMessage.success('个人资料已更新');
  } finally {
    profileLoading.value = false;
  }
};

const changePassword = async () => {
  if (!pwdForm.oldPassword || !pwdForm.newPassword || !pwdForm.confirmPassword) {
    ElMessage.warning('请完整填写密码信息');
    return;
  }
  if (pwdForm.newPassword.length < 6) {
    ElMessage.warning('新密码至少 6 位');
    return;
  }
  if (pwdForm.newPassword !== pwdForm.confirmPassword) {
    ElMessage.warning('两次输入的新密码不一致');
    return;
  }
  passwordLoading.value = true;
  try {
    await request.post('/auth/change-password', pwdForm);
    ElMessage.success('密码修改成功');
    pwdForm.oldPassword = '';
    pwdForm.newPassword = '';
    pwdForm.confirmPassword = '';
    await authStore.verifyToken();
  } finally {
    passwordLoading.value = false;
  }
};

fillProfileForm();
</script>

<style scoped>
.profile-page {
  padding-top: 6px;
}

.profile-hero {
  display: flex;
  justify-content: space-between;
  gap: 18px;
  align-items: center;
}

.hero-profile-actions {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  justify-content: flex-end;
}

.profile-grid {
  display: grid;
  grid-template-columns: 300px minmax(0, 1fr);
  gap: 22px;
}

.profile-card {
  padding: 26px;
  position: relative;
  overflow: hidden;
}

.profile-card h2,
.profile-card h3 {
  margin: 0 0 14px;
}

.profile-card > p,
.card-subtitle,
.card-title-row p {
  color: var(--text-secondary);
  margin: 0 0 18px;
}

.profile-avatar {
  width: 86px;
  height: 86px;
  border-radius: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 34px;
  font-weight: 900;
  background: var(--gradient-main);
  box-shadow: var(--shadow-card);
  margin-bottom: 20px;
}

.profile-status,
.form-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.profile-detail,
.password-card {
  grid-column: 2;
}

.card-title-row {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 18px;
}

.detail-list {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.detail-list div {
  padding: 16px;
  border-radius: 18px;
  background: var(--surface-muted);
  border: 1px solid var(--border-color);
}

.detail-list span {
  display: block;
  margin-bottom: 8px;
  color: var(--text-muted);
  font-size: 12px;
  font-weight: 800;
}

.detail-list strong {
  color: var(--text-primary);
  overflow-wrap: anywhere;
}

.profile-form {
  max-width: 680px;
}

.password-card .el-button {
  min-width: 160px;
}

@media (max-width: 900px) {
  .profile-grid {
    grid-template-columns: 1fr;
  }

  .profile-detail,
  .password-card {
    grid-column: auto;
  }
}

@media (max-width: 640px) {
  .profile-hero,
  .card-title-row {
    align-items: flex-start;
    flex-direction: column;
  }

  .hero-profile-actions,
  .hero-profile-actions > * {
    width: 100%;
  }

  .detail-list {
    grid-template-columns: 1fr;
  }
}
</style>

// glasses-management-frontend-react/src/pages/Profile.tsx
import React, { useState, useEffect } from 'react';
import { Button, Input, Form, Tag, message, Space } from 'antd';
import { useDispatch } from 'react-redux';
import { AppDispatch } from '@/store';
import { verifyToken } from '@/features/auth/authSlice';
import { useAuth } from '@/hooks/useAuth';
import { authAPI } from '@/features/auth/authAPI';

const Profile: React.FC = () => {
  const dispatch = useDispatch<AppDispatch>();
  const auth = useAuth();
  const [editing, setEditing] = useState(false);
  const [profileLoading, setProfileLoading] = useState(false);
  const [passwordLoading, setPasswordLoading] = useState(false);
  const [profileForm] = Form.useForm();
  const [pwdForm] = Form.useForm();

  const displayName = auth.realName || auth.username || '-';
  const initial = (displayName || '用').charAt(0);
  const roleLabel = auth.role === 'admin' ? '超级管理员' : '商户账号';

  useEffect(() => {
    profileForm.setFieldsValue({
      username: auth.username || '',
      phone: auth.phone || '',
      realName: auth.realName || '',
    });
  }, [auth.username, auth.phone, auth.realName, profileForm]);

  const startEdit = () => {
    profileForm.setFieldsValue({
      username: auth.username || '',
      phone: auth.phone || '',
      realName: auth.realName || '',
    });
    setEditing(true);
  };

  const cancelEdit = () => {
    profileForm.setFieldsValue({
      username: auth.username || '',
      phone: auth.phone || '',
      realName: auth.realName || '',
    });
    setEditing(false);
  };

  const saveProfile = async () => {
    try {
      const values = await profileForm.validateFields();
      setProfileLoading(true);
      try {
        await authAPI.updateProfile({
          realName: values.realName,
          phone: values.phone,
        });
        message.success('个人资料已更新');
        await dispatch(verifyToken());
        setEditing(false);
      } finally {
        setProfileLoading(false);
      }
    } catch {
      // validation handled
    }
  };

  const changePassword = async () => {
    try {
      const values = await pwdForm.validateFields();
      setPasswordLoading(true);
      try {
        await authAPI.changePassword({
          oldPassword: values.oldPassword,
          newPassword: values.newPassword,
          confirmPassword: values.confirmPassword,
        });
        message.success('密码修改成功');
        pwdForm.resetFields();
        await dispatch(verifyToken());
      } finally {
        setPasswordLoading(false);
      }
    } catch {
      // validation handled
    }
  };

  return (
    <div className="page-shell profile-page">
      <section
        className="page-hero glass-card profile-hero"
        style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 18 }}
      >
        <div>
          <h1 className="page-heading" style={{ margin: 0 }}>个人主页</h1>
          <p className="page-title-en">ACCOUNT PROFILE</p>
        </div>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <Button onClick={startEdit}>{editing ? '继续编辑' : '编辑资料'}</Button>
        </div>
      </section>

      <div className="profile-grid">
        {/* Avatar Card */}
        <section className="profile-card glass-card identity-card" style={{ textAlign: 'center' }}>
          <div className="profile-avatar" style={{ margin: '0 auto 20px' }}>
            {initial}
          </div>
          <h2>{displayName}</h2>
          <p>{auth.username || '-'}</p>
          <div className="profile-status" style={{ justifyContent: 'center' }}>
            <Tag color={auth.role === 'admin' ? 'red' : 'green'}>{roleLabel}</Tag>
            {auth.disabled ? <Tag color="warning">已封禁</Tag> : <Tag color="success">正常</Tag>}
          </div>
        </section>

        {/* Account Info */}
        <section className="profile-card glass-card profile-detail">
          <h3>账号信息</h3>
          <p>维护你的登录用户名、手机号和展示名称。</p>

          {!editing ? (
            <div className="detail-list">
              {[
                { label: '显示名称', value: auth.realName || '-' },
                { label: '用户名', value: auth.username || '-' },
                { label: '手机号', value: auth.phone || '-' },
                { label: '角色', value: roleLabel },
                { label: '注册时间', value: auth.createTime || '-' },
              ].map((item) => (
                <div key={item.label}>
                  <span>{item.label}</span>
                  <strong>{item.value}</strong>
                </div>
              ))}
            </div>
          ) : (
            <Form form={profileForm} layout="vertical" style={{ maxWidth: 680 }}>
              <Form.Item label="显示名称" name="realName">
                <Input maxLength={50} placeholder="用于页面展示的名称" showCount />
              </Form.Item>
              <Form.Item label="用户名" name="username">
                <Input maxLength={30} placeholder="3-30 位，可用于登录" />
              </Form.Item>
              <Form.Item label="手机号" name="phone">
                <Input maxLength={11} placeholder="请输入手机号，也可用于登录" />
              </Form.Item>
              <Space>
                <Button onClick={cancelEdit}>取消</Button>
                <Button type="primary" loading={profileLoading} onClick={saveProfile}>保存资料</Button>
              </Space>
            </Form>
          )}
        </section>

        {/* Password */}
        <section className="profile-card glass-card password-card">
          <h3>修改密码</h3>
          <p className="card-subtitle">
            建议定期更换密码，避免继续使用默认密码。
          </p>
          <Form form={pwdForm} layout="vertical" style={{ maxWidth: 680 }}>
            <Form.Item label="当前密码" name="oldPassword">
              <Input.Password placeholder="请输入当前密码" />
            </Form.Item>
            <Form.Item label="新密码" name="newPassword">
              <Input.Password placeholder="至少 6 位" />
            </Form.Item>
            <Form.Item label="确认新密码" name="confirmPassword">
              <Input.Password placeholder="请再次输入新密码" />
            </Form.Item>
            <Button type="primary" loading={passwordLoading} onClick={changePassword} style={{ minWidth: 160 }}>
              保存新密码
            </Button>
          </Form>
        </section>
      </div>
    </div>
  );
};

export default Profile;
